# Machine Learning

In [56]:
#imports - one single time for the entire notebook
import torch
import math
import numpy as np

## K-means clustering

In [57]:
def k_means_clustering(points, k, initial_centroids, max_iterations) -> list[tuple[float, ...]]:
    """
    Perform k-means clustering on `points` into `k` clusters.
    points: tensor of shape (n_points, n_features)
    initial_centroids: tensor of shape (k, n_features)
    max_iterations: maximum number of iterations
    Returns a list of k centroids as tuples, rounded to 4 decimals.
    """
    # Convert to tensors
    points_t = torch.as_tensor(points, dtype=torch.float)
    centroids = torch.as_tensor(initial_centroids, dtype=torch.float)
    # Your implementation here
    nb_points = points_t.size()[0]


    def distance(a,b):
        m = len(a)
        return sum([(a[i]-b[i])**2 for i in range(m)])
    
    for _ in range(max_iterations):
        map ={}
        for i in range(nb_points):
            l = (torch.argmin((torch.tensor([distance(points_t[i],centroids[j]) for j in range(k)])))).item()
            if l not in map :
                map[l] = [points_t[i]]
            else:
                map[l].append(points_t[i])


        for i in range(k):
            if i in map:
                centroids[i] = sum(map[i])/(len(map[i]))

    return centroids



In [58]:
points = [(1, 2), (1, 4), (1, 0), (10, 2), (10, 4), (10, 0)]
k = 2
initial_centroids = [(1, 1), (10, 1)]
max_iterations = 10

In [59]:
k_means_clustering(points, k, initial_centroids, max_iterations)

tensor([[ 1.,  2.],
        [10.,  2.]])

## Linear Regression Using Normal Equation

In [60]:
def linear_regression_normal_equation(X, y) -> torch.Tensor:
    """
    Solve linear regression via the normal equation using PyTorch.
    X: Tensor or convertible of shape (m,n); y: shape (m,) or (m,1).
    Returns a 1-D tensor of length n, rounded to 4 decimals.
    """
    X_t = torch.as_tensor(X, dtype=torch.float)
    y_t = torch.as_tensor(y, dtype=torch.float).reshape(-1,1)
    # Your implementation here
    res = torch.matmul(torch.matmul(torch.linalg.inv(torch.matmul(torch.transpose(X_t,0,1),X_t)),torch.transpose(X_t,0,1)),y_t)
    return torch.round(res,decimals=4)


In [61]:
X = [[1, 1], [1, 2], [1, 3]]
y = [1, 2, 3]

In [62]:
linear_regression_normal_equation(X, y)

tensor([[0.],
        [1.]])

## Linear Regression Using Gradient Descent

In [249]:
def linear_regression_gradient_descent(X, y, alpha, iterations) -> torch.Tensor:
    """
    Perform linear regression using gradient descent with PyTorch autograd.

    Args:
        X: Feature matrix (m, n) - can be tensor or array-like
        y: Target vector (m,) - can be tensor or array-like  
        alpha: Learning rate
        iterations: Number of gradient descent iterations
    
    Returns:
        Learned weights as a 1D tensor of shape (n,)
    """
    X_t = torch.as_tensor(X, dtype=torch.float32)
    y_t = torch.as_tensor(y, dtype=torch.float32).reshape(-1, 1)
    m, n = X_t.shape


    class Model(torch.nn.Module):
        def __init__(self):
            super().__init__()
            self.theta = torch.nn.Parameter(torch.zeros((n, 1), requires_grad=True))

        def forward(self, x):
            return torch.matmul(x,self.theta)

        
    model = Model()
    optim = torch.optim.SGD(params=model.parameters(), lr=alpha)
    for _ in range(iterations):
        model.train()
        prediction = model(X_t)
        loss = (1/(2*m)) * ((prediction - y_t)**2).sum()
        optim.zero_grad()
        loss.backward()
        optim.step()

    return model.theta.detach()

In [250]:
X = np.array([[1, 1], [1, 2], [1, 3]])
y = np.array([3, 5, 7])
alpha = 0.1
iterations = 1000

In [251]:
res = linear_regression_gradient_descent(X, y, alpha, iterations) 

In [252]:
print(res)

tensor([[1.0000],
        [2.0000]])
